components:
  # - name: index-management
  #   integ-test:
  #     dependencies:
  #       - job-scheduler
  #       - alerting
  #     test-configs:
  #       - with-security
  #       - without-security
  #   bwc-test:
  #     dependencies:
  #     test-configs:
  #       - with-security
  #       - without-security
  # - name: anomaly-detection
  #   integ-test:
  #     dependencies:
  #       - job-scheduler
  #       - alerting
  #     test-configs:
  #       - with-security
  #       - without-security
  #   bwc-test:
  #     dependencies:
  #     test-configs:
  #       - with-security
  #       - without-security
  # - name: asynchronous-search
  #   integ-test:
  #     dependencies:
  #       - job-scheduler
  #       - alerting
  #     test-configs:
  #       - with-security
  #       - without-security
  #   bwc-test:
  #     dependencies:
  #     test-configs:
  #       - with-security
  #       - without-security
  # - name: sql
  #   integ-test:
  #     dependencies:
  #       - job-scheduler
  #       - alerting
  #     test-configs:
  #       - with-security
  #       #- without-security
  #   bwc-test:
  #     dependencies:
  #     test-configs:
  #       - with-security
  #       - without-security
  - name: alerting
    integ-test:
      dependencies:
        - job-scheduler
        - alerting
      test-configs:
        - with-security
        - without-security
    bwc-test:
      dependencies:
      test-configs:
        - with-security
        - without-security
  # - name: k-NN
  #   integ-test:
  #     dependencies:
  #       - job-scheduler
  #       - alerting
  #     test-configs:
  #       - with-security
  #       - without-security
  #   bwc-test:
  #     dependencies:
  #     test-configs:
  #       - with-security
  #       - without-security
  # - name: dashboards-notebooks
  #   integ-test:
  #     dependencies:
  #       - job-scheduler
  #       - alerting
  #     test-configs:
  #       #- with-security
  #       - without-security
  #   bwc-test:
  #     dependencies:
  #     test-configs:
  #       - with-security
  #       #- without-security
schema-version: '1.0'
